<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title>ASC Motors</title>
    <link rel="stylesheet" href="css/Header.CSS">
</head>
<body>

    <nav>
        <a href="index.php">Home |</a>
        <a href="Products.php">Products |</a>
        <a href="Gallery.php">Gallery |</a>
        <a href="contact.php">Contact Us</a>

        <div class="icon-container">
            <a href="cart.php"><?php include 'BootstrapIcons.php'; ?></a>
        </div>

        <div class="login-button">
            <a href = 'Login.php'>Login</a>
        </div>
    </nav>

</body>
</html>
