<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ASC Motors</title>
    <link rel="stylesheet" href="Header.css">
</head>
<body>

    <nav>
        <a href="index.php">Home |</a>
        <a href="search.php">Page 2 |</a>
        <a href="page3.php">Page 3 |</a>
        <a href="page4.php">Page 4 |</a>
        <a href="contact.php">Contact Us</a>
    </nav>

</body>
</html>
